config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  root 'statics#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'about', to: 'statics#about'
  get 'contact', to: 'statics#contact'

  devise_for :users
  
  resources :images, only: [:create]
  resources :sections, only: [:create, :update, :destroy] do
    patch 'change_index', on: :member
  end
  resources :books, only: [:new, :update, :destroy] do
  	get 'editor', on: :member
    get 'delete-cover', on: :member
  end
end

app/views/shared/_flash.html.erb
<div class="errors">
	<% if flash.present? %>
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %> fade in widget-inner">
	      <button type="button" class="close" data-dismiss="alert">×</button>
	      <%= value %>
	    </div>
	  <% end %>
	<% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">

  	<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
	    </button>
			<span class='navbar-brand'>Book Build</span>
  	</div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
	    <ul class="nav navbar-nav navbar-left">

        <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Books <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add a Book', new_book_path %></li>
              <li role="separator" class="divider"></li>
              <% current_user.books.order(:title).each do |book| %>
                <li><%= link_to book.title, editor_book_path(book) %></li>
              <% end %>
            </ul>
          </li>

        <% else %>
      
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>

        <% end %>
        
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>

    </div><!-- /.navbar-collapse -->

  </div>
</nav>